name: gthr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/gthr_logo.png
    - assets/gthr_logo2.png
    - assets/event_1.jpg
    - assets/event_2.jpg
    - assets/user_1.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
